#flask-app.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-reg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-reg
  template:
    metadata:
      labels:
        app: flask-reg
    spec:
      containers:
        - name: flask-reg
          image: flask-reg:latest  # This should match the image name of kubernettes image
          imagePullPolicy: Never
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: registration-service
spec:
  type: NodePort
  selector:
    app: registration
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000